[project]
name = "researchweb"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "networkx",
    "pyvis",
    "python-dotenv",
    "gradio",
    "google-genai",
]

[tool.uv.workspace]
members = [
    "streamlit-demo",
]
